# Font
font_family		CaskaydiaCove Nerd Font Mono
font_size 		13.0
modify_font 		underline_position -2
modify_font 		underline_thickness 150%
modify_font 		strikethrough_thickness 200%
modify_font 		strikethrough_position 2px

# Dracula Theme
foreground		#f8f8f2
background		#282a36
selection_foreground	#ffffff
selection_background	#44475a
cursor			#f8f8f2
cursor_text_color	#282a36
background_opacity	0.2
background_blur		32


color0	#21222c
color1	#ff5555
color2	#59fa7b
color4	#bd93f9
color5	#ff79c6
color6	#8be9fd
color7	#f8f8f2
color8	#6272a4
color9	#ff6e6e
color10	#69ff94
color11	#ffffa5
color12	#d6acff
color13	#ff92df
color14	#a4ffff
color15	#ffffff

#cursor Animation
cursor_shape			beam
cursor_blink_interval		0.5
cursor_stop_blinking_after	0
cursor_beam_thickness 		1.5
cursor_trail			1
cursor_trail_decay 		0.1 0.4
cursor_trail_start_threshold 	2
cursor_trail_color 		none


#            SCROLLBAR
#scrollback
scrollback_lines		10000
scrollbar			scrolled
scrollbar_interactive		yes
scrollbar_jump_on_click		yes
scrollbar_width			0.5
scrollbar_hover_width		1
scrollbar_handle_opacity	0.5
scrollbar_radius 		0.3
scrollbar_gap 			0.1
scrollbar_min_handle_height 	2
scrollbar_hitbox_expansion 	0.25
scrollbar_track_opacity 	0
scrollbar_track_hover_opacity 	0.1
scrollbar_handle_color 		foreground



#window padding
window_padding_width		8


# Kitty keymaps :3
map f1 create_marker
map f2 remove_marker


