monitor=,1280x1024,auto,1

exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = waybar
exec-once = kitty

$terminal = kitty

bind = SUPER, Return, exec, $terminal
bind = SUPER, Q, killactive
bind = SUPER SHIFT, E, exit

general {
	gaps_in = 5
	gaps_out = 10
	border_size = 2
}

decoration {
	rounding = 10
	active_opacity = 1.0
	inactive_opacity = 1.0
	blur {
		enabled = true
		size = 8
		passes = 2
	}
}

